#! /usr/bin/env bash

set -eux

sudo apt-get update
sudo apt-get install -y  \
  coreutils \
  apt-transport-https \
  ca-certificates \
  gnupg-agent \
  software-properties-common \
  openssl

# Install chrony
sudo apt-get install -y chrony
sudo chronyc -a 'burst 4/4' && sudo chronyc -a makestep
sudo systemctl enable chrony
sudo systemctl start chrony

# Install qemu
sudo apt-get install -y qemu qemu-kvm

# Enable nested virtualization
sudo bash -c 'cat << EOF > /etc/modprobe.d/qemu-system-x86.conf
options kvm-intel nested=y enable_apicv=n
EOF'
echo "Reboot required"

# Install Docker

sudo mkdir -m 0755 -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo echo \
  "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list

sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io jq
sudo groupadd docker
sudo usermod -aG docker ubuntu
sudo usermod -aG docker metal3ci
sudo systemctl enable docker
sudo systemctl restart docker