From golang

RUN apt update -y
RUN apt install file -y

RUN GO111MODULE=on go get github.com/mikefarah/yq/v3

RUN wget https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-openstack/master/templates/env.rc -O /tmp/env.rc

CMD /bin/bash -c "source /tmp/openstackrc && . /tmp/env.rc clouds.yaml os_instance_1 && env | grep -i openstack"

